version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: Alumne1234*
      MYSQL_PASSWORD: Alumne1234*
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '81:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Alumne1234*
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
        #- ./varLogApache2:/var/log/apache2
        #- ./etcApache2:/etc/apache2
        #- ./varLibApache2:/var/lib/apache2
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Alumne1234*
    networks:
      - wpsite
networks:
  wpsite:

